eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9991
spring:
  application:
    name: tree-house-zuul-dev
  redis:
    database: 4
    host: 120.78.170.118 #120.55.167.171  120.78.170.118
    port: 6379
    password: 123456
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-dev
    api-friend:
      path: /api-friend/**
      serviceId: friend-dev
    api-userGoods:
      path: /api-goods/**
      serviceId: user-goods-dev
    api-treeHouse:
      path: /api-treeHouse/**
      serviceId: tree-house-dev
    api-message:
      path: /api-message/**
      serviceId: message-dev
    api-fishing:
      path: /api-fishing/**
      serviceId: fishing-dev
    api-welfare:
      path: /api-welfare/**
      serviceId: welfare-dev
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
user-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
friend-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
user-goods-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
tree-house-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
message-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
fishing-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
welfare-dev:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
hystrix:
    #  command:
      #    default:
      #      execution:
      #        isolation:
      #          thread:
  #            timeoutInMilliseconds: 60000
  user-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  friend-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  user-goods-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  tree-house-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  message-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  fishing-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  welfare-dev:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000

