feign-service:
  user: user-dev
  user-goods: user-goods-dev
  friend: friend-dev
  message: message-dev
  welfare: welfare-dev
server:
    port: 11004
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://bj-cdb-kkucszns.sql.tencentcdb.com:62815/tongzhu_treehouse_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: rP3Za18k3Mw18gDJ
      hikari:
          data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
              maxLifetime: 1800000
              idleTimeout: 600000
  application:
    name: tree-house-dev
  redis:
      database: 4
      host: 120.78.170.118 #120.55.167.171 120.78.170.118
      port: 6379
      password: 123456
      lettuce:
        shutdown-timeout: 30000ms
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.tongzhu.treehouse.model
  mapper-locations: classpath:mapping/**/*Mapper.xml

#pagehelper分页工具
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#logging:
#  level:
#    com.tongzhu.treehouse.mapper : debug
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000
#feign:
#  hystrix:
#    enabled: true
## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070