feign-service:
  user: user
  user-goods: user-goods
  tree-house: tree-house
  friend: friend
  welfare: welfare
server:
    port: 9093
    tomcat:
      max-threads: 500
netty:
  server:
    port: 9099
    ssl:
      port: 9433
spring:
  application:
    name: message
  redis:
    database: 6
    host: 10.66.170.87
    port: 6379
    password: 6^xAq@MWLlM!RSVP
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.141.25.60
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://10.141.25.60:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000
